### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by elazar** [comment]
This version should also be included in the section of allowed failures since the build is in a constant state of flux.

**Comment by TomasVotruba** [comment]
I guess that would make sense if the build is failing ATM.

**Comment by elazar** [comment]
It may not be currently failing, but that's not the only issue of consequence. Changes in the nightly PHP build could cause Travis builds to fail because of misbehaviors in PHP rather than in DbUnit. As such, until PHP 7 is stable, I believe the allowed failures section is the appropriate place for it.

**Comment by TomasVotruba** [comment]
I see the point. This should have been only consistent with commit to phpunit, https://github.com/sebastianbergmann/phpunit/commit/d5ecb0a2451e9c4c8b8e0e9356707371cb4f4b49

**Comment by TomasVotruba** [comment]
@elazar  So should it really be different to other phpunit repos?

**Comment by elazar** [comment]
I'll defer to @sebastianbergmann if he wants to weigh in, but I suspect phpunit could have the same issue I described above.

**Pull request closed without merging**
