### PR TITLE
Add functionality to read concatenated xml files

### PR DESCRIPTION
**Pull request by davidmpaz**
Hi,

Please could be considered this?

There are tools that generate xml files concatenated, it could be
usefull to allow for reading such files since it can save time and
effort on xml fixture generation, even when such files are not valid
xml documents.

The motivation behind can be seen at: https://github.com/netz98/n98-magerun/issues/545

Many thanks in advance.

### CODE REVIEW

**Comment by davidmpaz** [comment]
Closing/Reopening to trigger Travis build.

**Comment by sebastianbergmann** [comment]
Can you elaborate why `PHPUnit_Extensions_Database_DataSet_CompositeDataSet` does not solve your problem?

**Comment by davidmpaz** [comment]
With `PHPUnit_Extensions_Database_DataSet_CompositeDataSet` we are adding datasets that comes in different xml files. In this case, it is one file. The output from the export tool is two xml documents but concatenated in one file.

**Comment by elazar** [comment]
> even when such files are not valid xml documents

I think this is actually a good reason not to support this feature. If such tools want to be interoperable with other tools and libraries, the onus should be on the former to export valid output.

**Comment by davidmpaz** [comment]
Point taken. Thanks.

**Pull request closed without merging**
